import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const mySchema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'collecte',
      columns: [
        { name: 'unite', type: 'number' },
        { name: 'poids_unitaire', type: 'number' },
        { name: 'montant_achat', type: 'number' },
        { name: 'prix_fg_kg', type: 'number' },
        { name: 'etat_route', type: 'string' },
        { name: 'quantite_collecte', type: 'number' },
        { name: 'niveau_approvisionement', type: 'string' },
        { name: 'statut', type: 'string' },
        { name: 'observation', type: 'string' },
        { name: 'etat', type: 'string' },
        { name: 'enquete', type: 'number' },
        { name: 'produit', type: 'string' },
        { name: 'destination_finale', type: 'number' },
        { name: 'num_fiche', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'grossistes',
      columns: [
        { name: 'unite_stock', type: 'number' },
        { name: 'poids_moyen_unite_stock', type: 'number' },
        { name: 'poids_stock', type: 'number' },
        { name: 'unite_achat', type: 'string' },
        { name: 'nombre_unite_achat', type: 'number' },
        { name: 'poids_moyen_unite_achat', type: 'number' },
        { name: 'poids_total_achat', type: 'number' },
        { name: 'localite_achat', type: 'string' },
        { name: 'fournisseur_achat', type: 'string' },
        { name: 'unite_vente', type: 'string' },
        { name: 'nombre_unite_vente', type: 'number' },
        { name: 'poids_moyen_unite_vente', type: 'number' },
        { name: 'poids_total_unite_vente', type: 'number' },
        { name: 'prix_unitaire_vente', type: 'number' },
        { name: 'client_vente', type: 'number' },
        { name: 'client_principal', type: 'string' },
        { name: 'fournisseur_principal', type: 'string' },
        { name: 'niveau_approvisionement', type: 'string' },
        { name: 'statut', type: 'string' },
        { name: 'observation', type: 'string' },
        { name: 'enquete', type: 'number' },
        { name: 'produit', type: 'string' },
        { name: 'localite_origine', type: 'number' },
        { name: 'num_fiche', type: 'string' },
      ],
    }),
    tableSchema({
      name: 'consommation',
      columns: [
        { name: 'unite', type: 'number' },
        { name: 'poids_unitaire', type: 'string' },
        { name: 'prix_mesure', type: 'number' },
        { name: 'prix_fg_kg', type: 'number' },
        { name: 'prix_kg_litre', type: 'number' },
        { name: 'niveau_approvisionement', type: 'string' },
        { name: 'statut', type: 'string' },
        { name: 'observation', type: 'string' },
        { name: 'enquete', type: 'number' },
        { name: 'produit', type: 'string' },
        { name: 'num_fiche', type: 'string' },
      ],
    }),
  ],
});
